### ISSUE TITLE
Basemap uses depreciated shapefiles::read.shapefile, read_sf would be better

### ISSUE THREAD

**Issue by SimonDedman** [SimonDedman/gbm.auto#49]
cropshp <- read_sf("./CroppedMap/Crop_Map.shp") 
is better but will that work for gbm.map etc?
would allow removal of rgdal etc dependency (tho still used by sf etc)
need to add sf dependency
better going forward.

**Comment by SimonDedman** [comment]
# st_crs(cropshp) <- 4326
need to set crs but won't know what that should be. Could do algorithmically somehow?
should be lambert equal area projection? any equal area? why? see https://github.com/jmlondon/ptolemy crawl example alaskan seals

**Comment by jfroeschke** [comment]
Simon:

This repo https://github.com/jfroeschke/shapefileUpload has a basic example
of detecting a shapefile projection and reprojecting to plot in leaflet.

Hope this helps

John

**Comment by SimonDedman** [comment]
Thanks John, looks very interesting, trying to get my head around it now.
Your code is so well laid out! I need to up my game...
Looks like mod_shpPoly.R takes any unknown format shapefile set and deduces its points/lines/polys format and projects to WGS84 with the correct symbology?

The issue I'm having (possibly: I might NOT need to do this) is that I was following this excellent tutorial for plotting track files (https://jmlondon.github.io/crwexampleakbs/analysis.html) which includes this:

> 
These data are still in the WGS84 geographic coordinate system. Projecting the data into a more appropriate coordinate reference system is strongly encouraged and needed for some functionality in crawl. This is especially important when/if data cross the 180 line, are spread over a large latitudinal range, or within the polar regions.
`
sf_locs <- sf_locs %>% sf::st_transform(3571)`

Which I ended up getting to work with 4326 projection for the North Atlantic, after cycling through various CRS projection options in QGis. But I'm thinking, long term, it would be nice to write some code which selects the most appropriate projection based on your data. My gbm.basemap function already crops the global coastline shapefile to the data so this would complement that.

Not sure if the project you shared does that but it does look like it contains a wonderful guide to help me start getting maps online, which I'm going to need to do very soon, so thanks!

**Comment by SimonDedman** [comment]
technical term: needs to be "a valid EPSG value (numeric)" (st_crs help)
https://www.epsg-registry.org says 4326 is WGS 84
QGis says 3571is lambert azimuthal equal area. EPSG says it's ProjectedCRS also
Need to be equal area? Lambert equal area? 4326 worked fine across 0 line as clipped by gbmbasemap but isn't equal area.

Find out from Josh London WHY a projected CRS (rather than a GeodeticCRS (geographic 2D)) is needed for crawl, for what functionality. Crossing the 180 line maybe but what about the 0 line? Find out the technicalities behind this choice process
THEN
Investigate EPSG more. Use https://www.epsg-registry.org/ mapping box & query filter to list potential candidates. Can API to this from R since this query filter process is functionally what I'm trying to code for? Possibly... Looks like the results of that query all occur within the user set bounds, but don't appear to be sorted by closest match, so if you set bounds for the whole globe, it would just list ALL the database alphabetically.

Equal Earth:
CoordinateConversion
greenwich 8854
americas 8855
asiapacific 8856
Projected greenwich 8857
Projected americas 8858
Projected Asia pacific 8859

**Comment by jfroeschke** [comment]
Simon, you are correct on the general intent of   mod_shpPoly.R.  However,
much of that code is related or only required for a shiny app.  In general
you could use a similar approach to determine and reproject into the
appropriate CRS depending on location, range, or other factors.  I dont
have any guidance on what coordinate system to use where as my work is
usually within a small geographic area.  As you will notice, my code uses
both sp and sf syntax which I dont recommend.  sf is better I just don't
know it that well hence the mish mash of coding syntax.

**Comment by SimonDedman** [comment]
Thanks John. Looks like one possible universal workaround would be to use the new [Equal Earth projection](https://www.gislounge.com/equal-earth-map-projection/) - check it out, likely of general interest to a mapping guru such as yourself, if not known already.

**Comment by jfroeschke** [comment]
Its news to me and looks interesting.  Is it supported in an R package?

**Comment by SimonDedman** [comment]
I presume it would simply be:
`st_crs(natlantic4) <- n`
where n is:
CoordinateConversion greenwich 8854
CoordinateConversion americas 8855
CoordinateConversion asiapacific 8856
Projected greenwich 8857
Projected americas 8858
Projected Asia pacific 8859

(emphasis on the presume! But will hopefully try this week)

**Comment by SimonDedman** [comment]
```
> caltrawl2 <- st_transform(caltrawl, crs = 8858)
OGR: Corrupt data
Error in CPL_transform(x, crs$proj4string) : OGR error
In addition: Warning message:
In CPL_crs_from_epsg(as.integer(x)) :
  GDAL Error 6: EPSG PCS/GCS code 8858 not found in EPSG support files.  Is this a valid EPSG coordinate system?
> caltrawl2 <- st_transform(caltrawl, crs = 8855)
OGR: Corrupt data
Error in CPL_transform(x, crs$proj4string) : OGR error
In addition: Warning message:
In CPL_crs_from_epsg(as.integer(x)) :
  GDAL Error 6: EPSG PCS/GCS code 8855 not found in EPSG support files.  Is this a valid EPSG coordinate system?
```

Looks like it ain't gonna be so simple.

**Comment by SimonDedman** [comment]
```
> caltrawl2 <- st_transform(caltrawl, crs = 8858)
OGR: Corrupt data
Error in CPL_transform(x, crs$proj4string) : OGR error
In addition: Warning message:
In CPL_crs_from_epsg(as.integer(x)) :
  GDAL Error 6: EPSG PCS/GCS code 8858 not found in EPSG support files.  Is this a valid EPSG coordinate system?
> caltrawl2 <- st_transform(caltrawl, crs = 8855)
OGR: Corrupt data
Error in CPL_transform(x, crs$proj4string) : OGR error
In addition: Warning message:
In CPL_crs_from_epsg(as.integer(x)) :
  GDAL Error 6: EPSG PCS/GCS code 8855 not found in EPSG support files.  Is this a valid EPSG coordinate system?
```

Looks like it ain't gonna be so simple.

**Comment by SimonDedman** [comment]
`gbm.map` superseded by `gbm.mapsf`, which uses `st_read(dsn = shape)`, so removed `returnsf` param from `gbm.basemap`, should no longer need `shapefiles`.
