### ISSUE TITLE
Using gbm.auto with  R version 4.0.2 (2020-06-22)

### ISSUE THREAD

**Issue by DitteArp** [SimonDedman/gbm.auto#60]
Hi Simon,

I have problems downloading this package with the newest version of R (4.0.2). 
Do you know if the package works with this version?

Best regards,
Ditte

**Comment by SimonDedman** [comment]
Should do. Please review the diagnostic information which given when the
issue arises, and Google to see if that are existing solutions. Let me know
if you are unable to solve it, and if so please post all diagnostic info
here. Thanks.
Simon
