### ISSUE TITLE
ZI=TRUE/FALSE doesnt seem to be working

### ISSUE THREAD

**Issue by KristianBell** [SimonDedman/gbm.auto#65]
Running the code on a number of different datasets and ZI="CHECK" works fine but either ZI=TRUE or ZI=FALSE returns "Error in match.arg(ZI) : 'arg' must be NULL or a character vector". I have also tried "TRUE" and "FALSE".

**Comment by SimonDedman** [comment]
Painful. I only put `match.arg` in there for CRAN, it was working fine before.

If CHECK isn't resulting in the ZI state you want, and you need this immediately, please download an older version from GitHub for the time being. I'll put this on my todo list for next week.

Thanks for letting me know.

**Comment by SimonDedman** [comment]
Hopefully now fixed with [this](https://github.com/SimonDedman/gbm.auto/commit/abd3315e5ac7328800eccb8fe4067e58319deedc) push
