### ISSUE TITLE
Zero Inflation with Non-Default data families.

### ISSUE THREAD

**Issue by nffarabaugh** [SimonDedman/gbm.auto#74]
Hello I am having a hard time with automated zero-inflation checks with Non-Default data distribution families. 

I am working with ecological count data that is better described by Poisson distribution than Gaussian. Many of these data sets are zero inflated, however if I run the families as : 
   fam1 = c("bernoulli", "binomial", "poisson", "laplace", "gaussian"),
  fam2 = c( "poisson")

I am met with the error : gbm.fit(x = x, y = y, offset = offset, distribution = distribution, : Poisson requires the response to be a positive integer.

If I specify the families as: 

  fam1 = c(""binomial" ),
  fam2 = c( "poisson")

It seems like the binomial models are not run at all. 

Is there a transformation happening during this process that makes poisson distribution inappropriate for the zero inflation check= TRUE, process?  

Thanks for the help

**Comment by SimonDedman** [comment]
gbm.auto L419 poisson added as an exception.

**Comment by nffarabaugh** [comment]
Amazing Thanks!
