### ISSUE TITLE
Error in geography

### ISSUE THREAD

**Issue by JLHooten** [SimonDedman/gbm.auto#78]
Has anyone encountered the following error code when trying to use gbm.auto? 

> Error in s2_geography_from_wkb(x, oriented = oriented, check = check) :
          Evaluation error: Found 1 feature with invalid spherical geometry.
[2245] Loop 0 is not valid: Edge 3 crosses edge 5. 

Any assistance would be greatly appreciated. Thank you!

**Comment by SimonDedman** [comment]
Sorry Jackson, I only just saw this!
Per [this](https://stackoverflow.com/questions/68478179/how-to-resolve-spherical-geometry-failures-when-joining-spatial-data), try

```
sf::sf_use_s2(FALSE)
yer_object$geometry <- yer_object$geometry %>%
  s2::s2_rebuild() %>%
  sf::st_as_sfc()

```
