### ISSUE TITLE
gbm.factorplot: Pdp plot aesthetics help

### ISSUE THREAD

**Issue by nffarabaugh** [SimonDedman/gbm.auto#81]
In having to run many models with many Pdp plots I was wondering if there was a way to alter some of the aesthetics in the code for ease of use! First and foremost I would like the ability to alter axis labels and titles so the short hand I use while coding doesn't show up in my final plot meant for presentation or publication. Secondly I would like to be able to re-order the x axis for categorical variables so they are either 1) in order from high to low or 2) in some other logical order I specify such as factor level , rather than alphabetical. 

So for instance here is the pdp plot for some code as it is generated now: 
![image](https://user-images.githubusercontent.com/40179400/221057597-837228f6-02e2-4108-bf2a-7462b0be13c8.png)

I would like to be able to alter the names of both the x axis title and the labels, so that my sites have proper names and are readable, and two I would like the sites to appear on the plot from high to low! Thanks very much!

**Comment by nffarabaugh** [comment]
being able to call the plots and objects and thus able to make changes to it myself using ggplot commands or similar would be ideal! thus anyone with any issues that differ slightly could make bespoke changes to their plots. This might avoid issues such as the one in my plot above where several of the axis labels are missing as they are too long to fit in the plot area.

**Comment by SimonDedman** [comment]
L831 block loops through variables and does gaus_best_line_ plots and then saves the same underlying data as gaus_best_line_ csvs. csv data column, y, isn't the same as the plot. The plot Y axis labels are normalised around 0 it seems. Somehow? Y range above is > 0.4, maybe 0.45 or so.
Difference in the csv is 0.38.
how does gbm.plot work?
"common.scale	Logical. If TRUE, a common scale is used on the y axis"
default TRUE, changed to FALSE in gbm.auto already.

```
if (common.scale) {
            plot(predictors[[j]], responses[[j]], ylim = c(ymin, 
                ymax), type = "l", xlab = x.label, ylab = y.label, 
                ...)
        }
        else {
            plot(predictors[[j]], responses[[j]], type = "l", 
                xlab = x.label, ylab = y.label, ...)
        }
```

`gbm.plot(get(Gaus_Best_Model)`
but


```
if (linesfiles) {u <- match(get(Gaus_Best_Model)$contributions$var[p],
                                    get(Gaus_Best_Model)$gbm.call$predictor.names)
        plotgrid <- plot.gbm(get(Gaus_Best_Model), u, return.grid = TRUE)
        if (is.factor(plotgrid[,1])) {
          plotgrid[,1] <- factor(plotgrid[,1], levels = levels(get(Gaus_Best_Model)$gbm.call$dataframe[,get(Gaus_Best_Model)$gbm.call$gbm.x[u]]))}
        write.csv(plotgrid, row.names = FALSE, na = "",
                  file = paste0("./", names(samples[i]), "/Gaus_Best_line_",
                                as.character(get(Gaus_Best_Model)$contributions$var[p]),
                                ".csv"))}
```

**Comment by SimonDedman** [comment]
L853 in gbm.auto:
`# plotgrid[,2] <- plotgrid[,2] - mean(plotgrid[,2])`
have evidently done all of this before... ugh.
Added that line into gbm.auto so the centred bit is exported with the csv.

**Comment by SimonDedman** [comment]
see [this](https://github.com/SimonDedman/gbm.auto/blob/master/R/gbm.factorplot.R), please make edits as you see fit.

**Comment by SimonDedman** [comment]
https://wilkelab.org/ungeviz/reference/geom_hpline.html

**Comment by SimonDedman** [comment]
gbm.factorplot updated and added into gbm.auto at L844 & L918
